-- April 4th 2024
return {
    ["Mirage"] = {
        "Ancient Wanderer Lv 10.0Sp",
        "Aureus, The Great Lv 7.77N",
        "Eccentric Explorer Lv 200Sp",
        "Harbinger of the End Lv 49.9O",
        "Harbinger of the End Lv 499O",
        "Harbinger of the End Lv 500Sp",
        "Indolent Seer Lv 10.0Sp",
        "Kappa Lv 14O",
        "Kappa Lv 3.00O",
        "Kappa Lv 7O",
        "Kappa Lv 9O",
        "Lone Goblin Lv 300Sp",
        "Prisoner of the Mind Lv 150Sp",
        "Prisoner of the Mind Lv 250Sp",
        "Prisoner of the Mind Lv 500Sp",
        "Seer of Contempt Lv 20.0Sp",
        "The Silver King Lv 20O",
        "The Silver King Lv 49.9O",
 },
    ["Mines"] = {
        "Sealed Golem Lv 75K",
        "Stomag, Guardian of Hatred Lv 5K",
        "Serpent Lv 2K",
        "Basalt Demon Lv 999",
        "Great Golem Lv 850",
        "Golem of Flames Lv 850",
        "Golem of Flames Lv 775",
        "Golem of Flames Lv 725",
        "Basalt Barbarian Lv 625",
        "Basalt Blader Lv 625",
        "Gem Homunculi Lv 600",
        "Arcane Stone Knight Lv 525",
        "Basalt Barbarian Lv 500",
        "Arcane Stone Knight Lv 450",
        "Basalt Barbarian Lv 425",
        "Stone Knight Lv 400",
        "Basalt Barbarian Lv 375",
        "Stone Knight Lv 350",
        "Stone Underling Lv 325",
        "Gem Homunculi Lv 310",
        "Stone Knight Lv 300",
        "Stone Acolyte Lv 275",
        "Stone Knight Lv 250",
        "Stone Underling Lv 225",
        "Stone Underling Lv 170",
        "Stone Underling Lv 160",
        "Stone Underling Lv 130",
        "Stone Underling Lv 110",
        "XP Goblin Lv 99",
 },
    ["Underwater"] = {
        "Rotten Merman Lv 115B",
        "Rotten Merman Lv 65B",
        "Rotten Merman Lv 45B",
        "Effigy of Kleos Lv 100M",
        "Crimson Void Knight Lv 95M",
        "Knight of the Silent Abyss Lv 90M",
        "Seaking Lv 80M",
        "Crimson Void Knight Lv 75M",
        "Knight of the Silent Abyss Lv 50M",
        "Kronos, the Scorched Afterlife Lv 17.5M",
        "Lord of the Magma Lv 9M",
        "Mobius, Servant of the Seakings Lv 7.5M",
        "Crimsonwrath, Master of Rage Lv 6M",
        "Crimson Ozymandias Lv 4.7M",
        "Cerulean Ozymandias Lv 4.7M",
        "Cardinal of Poseidon Lv 4M",
        "Lost Astrologian Lv 4M",
        "Crimson Warlord Lv 4M",
        "Kronos, the Flood of Oblivion Lv 2.5M",
        "Cardinal of Treasure Lv 2M",
        "Corrupted Angel Lv 1.4M",
        "Infernal Visor Lv 1.3M",
        "Forlorne Executor Lv 975K",
        "Inferno Mage Lv 900K",
        "Abandoned Knight Lv 700K",
        "Damos, Guardian of Misfortune Lv 500K",
        "Dwelling Reaver Lv 375K",
        "Sunken Knight Lv 275K",
        "Sunken Knight Lv 250K",
        "Ocean Emissary Lv 125K",
        "Depths Fiend Lv 100K",
        "Aqua Mage Lv 85K",
        "Bluesteel Vanguard, Domine Lv 70K",
 },
    ["Void Tower"] = {
        "Amos, Priest of the Forgone Lv 666Sx",
        "Scythrax, the Sharpest One Lv 199Sx",
        "Agnar, Revoked Captain of the Dracoknights Lv 125Sx",
        "Almighty Ghost Lv 70Sx",
        "High Councillor of Amos Lv 45Sx",
        "Councillor of Amos Lv 31.0Sx",
        "Almighty Ghost Lv 30Sx",
        "Councillor of Amos Lv 24.9Sx",
        "Old Dissident Lv 11Sx",
        "Old Dissident Lv 5Sx",
        "Ghost of the Tower Lv 1Sx",
 },
    ["Hub of Rebirth"] = {
        "Gygax, Lord of Chance Lv 12.3K",
        "Monk Lv 6.4K",
        "Bone Harvester Lv 5K",
        "Yvexlorn, Ice Sunderer Lv 2.5K",
        "Red Rogue Lv 1.2K",
        "Kronos of the Future Lv 1K",
        "Ocean Delver Lv 560",
        "Viking of True Ice Lv 335",
        "XP Goblin Lv 99",
        "Monk Lv 64",
 },
    ["Glaurung"] = {
        "Boulder Sage Lv 20B",
        "The Knightmare Lv 10B",
        "Bombastic Ninja Lv 9.75B",
        "Bombastic Ninja Lv 6.75B",
 },
    ["Athenia"] = {
        "Poor Villager Lv 25K",
        "Aguman Lv 20K",
        "Stone Knight Lv 15K",
        "XP Goblin Lv 10K",
        "Clan Don Lv 10K",
        "Clan Prince Lv 9K",
        "Clan Bruiser Lv 8.8K",
        "Clan Bruiser Lv 8.5K",
        "Clan Bruiser Lv 8.2K",
        "Clan Bruiser Lv 8K",
        "Aleph, Master of the Blind Lv 7.5K",
        "Clan Disciple Lv 7K",
        "Ocean Champion Lv 6.7K",
        "Clan Disciple Lv 6.5K",
        "Druid of the Wind Lv 5.8K",
        "Wind Champion Lv 5.5K",
        "Ocean Champion Lv 4.8K",
        "Master of Oceans Lv 4.4K",
        "Master of Oceans Lv 4.3K",
        "Earth Champion Lv 4.2K",
        "Ocean Champion Lv 4.1K",
        "Ocean Champion Lv 4K",
        "Wind Champion Lv 4K",
        "Master of Oceans Lv 3.9K",
        "Ocean Disciple Lv 3.7K",
        "Ocean Disciple Lv 3.6K",
        "Ocean Disciple Lv 3.5K",
        "Master of Wind Lv 3.4K",
        "Wind Champion Lv 3.4K",
        "Ocean Disciple Lv 3.4K",
        "Flame Champion Lv 3.3K",
        "Master of Wind Lv 3.1K",
        "Master of Wind Lv 3K",
        "Master of Earth Lv 3K",
        "Wind Disciple Lv 2.9K",
        "Master of Earth Lv 2.9K",
        "Wind Disciple Lv 2.8K",
        "Earth Disciple Lv 2.8K",
        "Wind Disciple Lv 2.7K",
        "Wind Disciple Lv 2.6K",
        "Earth Disciple Lv 2.6K",
        "Earth Disciple Lv 2.5K",
        "Wind Disciple Lv 2.5K",
        "Wind Disciple Lv 2.4K",
        "Earth Disciple Lv 2.4K",
        "Earth Disciple Lv 2.1K",
        "Heckling Menace Lv 2K",
        "Athenian Villager Lv 2K",
        "Earth Disciple Lv 2K",
        "Earth Disciple Lv 1.9K",
        "Earth Disciple Lv 1.8K",
        "Heckling Menace Lv 1.7K",
        "Master of Flames Lv 1.7K",
        "Athenian Warrior Lv 1.5K",
        "Flame Disciple Lv 1.4K",
        "Flame Disciple Lv 1.3K",
        "Master of Flames Lv 1.2K",
        "Flame Disciple Lv 1.2K",
        "Athenian Warrior Lv 1.1K",
        "Flame Disciple Lv 1.1K",
        "Flame Disciple Lv 1K",
        "XP Goblin Lv 999",
        "Flame Disciple Lv 900",
        "Athenian Warrior Lv 900",
        "Flame Disciple Lv 800",
        "Flame Disciple Lv 700",
        "Flame Disciple Lv 600",
        "Athenian Merchant Lv 400",
 },
    ["Default"] = {
        "Knight of the Silent Abyss Lv 5M",
        "Kronos of the Past Lv 100K",
        "Sunken Captain Lv 60K",
        "Merman Soldier Lv 32.5K",
        "Merman Soldier Lv 17.5K",
        "Sunken Sniper Lv 13K",
        "Merman Lv 12.5K",
        "Merman Lv 10K",
        "Sunken Sniper Lv 8K",
        "Merman Lv 5.5K",
        "Sunken Swashbuckler Lv 4.5K",
        "Merman Lv 3.5K",
        "Sunken Swashbuckler Lv 2.5K",
        "Cloaked Deity Lv 1K",
        "Cloud Blader Lv 140",
        "Straw Demon Lv 130",
        "Gravemaster Lv 125",
        "Berserker Master Lv 125",
        "Castle Knight Lv 100",
        "Domino Lv 100",
        "Catseye Deity Lv 100",
        "Darkseed Rampart Lv 100",
        "Sage Knight Lv 90",
        "Berserker Lv 90",
        "Straw Demon Lv 80",
        "Bluesteel Sage Lv 80",
        "Armored Barbarian Lv 80",
        "Deity of Eyes Lv 80",
        "Sage Knight Lv 80",
        "Bone Harvester Lv 75",
        "Berserker Lv 70",
        "Castle Bandit Lv 70",
        "Viking Warlord Lv 70",
        "Chad Barbarian Lv 70",
        "Meddling Soul Lv 66",
        "Castle Bandit Lv 60",
        "Moon Bunny Lv 60",
        "Viking Lv 60",
        "Berserker Lv 60",
        "Black Iron Invader Lv 60",
        "Necromancer Lv 60",
        "Bluesteel Commander Lv 60",
        "Meddling Soul Lv 58",
        "Gigachad Ogre Lv 55",
        "Meddling Soul Lv 53",
        "Viking Lv 50",
        "Berserker Lv 50",
        "Meddling Soul Lv 45",
        "Gigachad Ogre Lv 44",
        "Castle Bandit Lv 40",
        "Meddling Soul Lv 40",
        "Great Ogre Lv 40",
        "Serpent Lv 40",
        "Highland Ogre Lv 40",
        "Highland Ogre Lv 37",
        "Great Ogre Lv 36",
        "Viking Leader Lv 35",
        "Gigachad Ogre Lv 34",
        "Highland Ogre Lv 33",
        "Great Ogre Lv 32",
        "Desert Knight Lv 31",
        "Viking Lv 30",
        "Ogam, Master of High Earth Lv 30",
        "Desert Merchant Lv 29",
        "Desert Knight Lv 29",
        "Great Ogre Lv 28",
        "Winter Hunter Lv 27",
        "Poor Villager Lv 25",
        "Yvexlorn, Ice Sunderer Lv 25",
        "The Gladiator Lv 25",
        "Gravekeeper Lv 25",
        "Ignister, Knight of the Dark Order Lv 25",
        "Ghost King Lv 25",
        "Gigachad Ogre Lv 24",
        "Winter Hunter Lv 24",
        "Shadow Assassin Lv 24",
        "Desert Knight Lv 23",
        "Villager Lv 22",
        "Berserker Lv 22",
        "Highland Ogre Lv 22",
        "Gigachad Ogre Lv 22",
        "Aguman Lv 20",
        "Servant of Fire Lv 20",
        "Sage Knight Lv 20",
        "Desert Knight Lv 19",
        "Highland Ogre Lv 18",
        "Farm Boy Lv 16",
        "Winter Hunter Lv 16",
        "Poor Villager Lv 15",
        "Snowman Lv 15",
        "Viking Lv 15",
        "Ogre King Lv 15",
        "Highland Ogre Lv 15",
        "Forgotten Soul, Yorick Lv 14",
        "Highland Ogre Lv 14",
        "Winter Mage Lv 14",
        "Goblin Captain Lv 13",
        "Ogre Lv 12",
        "Winter Nomad Lv 12",
        "The Sheriff Lv 11",
        "Pirate Goblin Lv 10",
        "Ghost Lv 10",
        "Snowman Lv 10",
        "Goblin Mage Lv 10",
        "Ghost Lv 9",
        "Ogre Lv 9",
        "Ghost Lv 8",
        "Snowman Lv 8",
        "Pirate Goblin Lv 8",
        "Berserker Lv 7",
        "Woodland Hunter Lv 7",
        "Bandit Chief Lv 7",
        "Pirate Goblin Lv 7",
        "Masked Fighter Lv 7",
        "Snowman Lv 7",
        "Ghost Lv 7",
        "Wizard of Arachnea Lv 6",
        "Bunny Lv 6",
        "Goblin Lv 5",
        "Thief Lv 5",
        "Shadow Assassin Lv 5",
        "Woodland Hunter Lv 4",
        "Thief Lv 4",
        "Thief Lv 3",
        "Shadow Assassin Lv 3",
        "Goblin Lv 3",
        "Bunny Lv 3",
        "Thief Lv 2",
        "Goblin Lv 2",
        "Poor Villager Lv 2",
        "Goblin Lv 1",
        "Villager Lv 1",
 },
    ["Citadel"] = {
        "Crimson Dragoon Lv 100B",
        "Azurewrath, Lord of  the Frost Lv 5B",
        "Frost Lich Lv 4.5B",
        "Azure Samurai Lv 3.75B",
        "Azurewrath Demon Lv 2.65B",
        "Fletch Lv 1.75B",
        "Old Mage Lv 1.65B",
        "Erikson Lv 1.65B",
        "Toothy Lv 1.25B",
        "Dragoon Lv 1B",
        "Fire Clan Hillfighter Lv 650M",
        "Frost Clan Hillfighter Lv 650M",
        "Forest Clan Hillfighter Lv 650M",
        "Lightning Clan Hillfighter Lv 650M",
        "Illuminous Mage Lv 520M",
        "Mystic of Destruction Lv 460M",
        "Master of Destruction Lv 400M",
        "Dracoknight Brutus Lv 380M",
        "Dracoknight of Glaurung Lv 320M",
        "Dracoknight of Smaug Lv 300M",
        "Illuminous Mage Lv 220M",
        "Champion of Azurewrath Lv 200M",
        "Dracoknight Brutus Lv 180M",
        "Mystic of Destruction Lv 160M",
        "Cloud Blader Lv 140M",
        "Dracoknight of Glaurung Lv 120M",
        "Dracoknight of Smaug Lv 100M",
 },
    ["Void"] = {
        "Alpha Biograft Delver Lv 11.1Sx",
        "Alpha Biograft Delver Lv 9.7Sx",
        "Vespertilio Lv 2.3Sx",
        "Gamma Crusader Lv 12.5Qn",
        "Mage of the Vile Truth Lv 6.3Qn",
        "Gamma Crusader Lv 6.3Qn",
        "Gamma Crusader Lv 3.2Qn",
        "Gamma Lancer Lv 2.7Qn",
        "Gamma Lancer Lv 1.3Qn",
        "Putridosaurus Lv 837Qd",
        "Treachery Master Lv 700Qd",
        "Putridosaurus Lv 53Qd",
        "Cthulhu Lv 25Qd",
        "Assassin of the Silent Abyss Lv 19Qd",
        "Stag of the Abyss Lv 13Qd",
        "Tarnished Guardia Lv 6Qd",
        "Eerie Jester Lv 2Qd",
        "Unholy Apparition Lv 1Qd",
        "Voidking Lv 900T",
        "Lord of the Void Lv 100T",
        "Guardian of the Fallen Crest Lv 83T",
        "Guardian of the Fallen Crest Lv 73T",
        "Guardian of the Fallen Crest Lv 53T",
        "Guardian of the Fallen Crest Lv 33T",
        "Assassin of the Silent Abyss Lv 25T",
        "Eerie Jester Lv 20T",
        "Guardian of the Fallen Crest Lv 17T",
        "Tokus, Viridian Scion Lv 12T",
        "Cvezkly, Scion of Matter Lv 10T",
        "Tyrant of Pride Lv 5T",
        "Master of Sloth Lv 4.5T",
        "Heart of Desire Lv 4T",
        "Lord of Greed Lv 3T",
        "Tyrant of Envy Lv 2.5T",
        "Envoy of Gluttony Lv 2T",
        "Tyrant of Wrath Lv 1T",
        "Gilded Assassin Lv 800B",
        "Gilded Assassin Lv 750B",
        "Baron Voidling Lv 700B",
        "Rebuked Voidlord Lv 600B",
        "Gilded Assassin Lv 550B",
        "Rebuked Voidlord Lv 500B",
        "Gilded Assassin Lv 450B",
        "Baron Voidling Lv 400B",
        "Gilded Assassin Lv 350B",
        "Baron Voidling Lv 300B",
        "Splendor Knight Lv 280B",
        "Splendor Knight Lv 220B",
        "Denizen of Plague Lv 170B",
        "Meeboid Lv 140B",
 },
    ["All"] = {
        "Abandoned Knight Lv 700K",
        "Agnar, Revoked Captain of the Dracoknights Lv 125Sx",
        "Aguman Lv 20",
        "Aguman Lv 20K",
        "Aleph, Master of the Blind Lv 7.5K",
        "Almighty Ghost Lv 30Sx",
        "Almighty Ghost Lv 70Sx",
        "Alpha Biograft Delver Lv 11.1Sx",
        "Alpha Biograft Delver Lv 411Qn",
        "Alpha Biograft Delver Lv 9.7Sx",
        "Alpha Biograft Delver Lv 97Qn",
        "Amos, Priest of the Forgone Lv 666Sx",
        "Ancient Wanderer Lv 10.0Sp",
        "Aqua Mage Lv 85K",
        "Arcane Stone Knight Lv 450",
        "Arcane Stone Knight Lv 525",
        "Archer of Artemis Lv 85K",
        "Armored Barbarian Lv 80",
        "Assassin of the Silent Abyss Lv 19Qd",
        "Assassin of the Silent Abyss Lv 25T",
        "Athenian Merchant Lv 400",
        "Athenian Villager Lv 2K",
        "Athenian Warrior Lv 1.1K",
        "Athenian Warrior Lv 1.5K",
        "Athenian Warrior Lv 900",
        "Aureus, The Great Lv 7.77N",
        "Aureus, The Tarnished Lv 10M",
        "Azure Samurai Lv 3.75B",
        "Azurewrath Demon Lv 2.65B",
        "Azurewrath, Lord of  the Frost Lv 5B",
        "Bandit Chief Lv 7",
        "Baron Voidling Lv 300B",
        "Baron Voidling Lv 400B",
        "Baron Voidling Lv 700B",
        "Basalt Barbarian Lv 375",
        "Basalt Barbarian Lv 425",
        "Basalt Barbarian Lv 500",
        "Basalt Barbarian Lv 625",
        "Basalt Blader Lv 625",
        "Basalt Demon Lv 999",
        "Berserker Lv 22",
        "Berserker Lv 50",
        "Berserker Lv 60",
        "Berserker Lv 7",
        "Berserker Lv 70",
        "Berserker Lv 90",
        "Berserker Master Lv 125",
        "Black Iron Invader Lv 60",
        "Bluesteel Commander Lv 60",
        "Bluesteel Sage Lv 80",
        "Bluesteel Vanguard, Domine Lv 70K",
        "Bombastic Ninja Lv 6.75B",
        "Bombastic Ninja Lv 9.75B",
        "Bone Harvester Lv 5K",
        "Bone Harvester Lv 75",
        "Boulder Sage Lv 20B",
        "Bunny Lv 3",
        "Bunny Lv 6",
        "Cardinal of Poseidon Lv 4M",
        "Cardinal of Treasure Lv 2M",
        "Castle Bandit Lv 40",
        "Castle Bandit Lv 60",
        "Castle Bandit Lv 70",
        "Castle Knight Lv 100",
        "Catseye Deity Lv 100",
        "Cerulean Ozymandias Lv 4.7M",
        "Chad Barbarian Lv 70",
        "Champion of Azurewrath Lv 200M",
        "Chronobonum, Everangel Lv 10T",
        "Clan Bruiser Lv 8.2K",
        "Clan Bruiser Lv 8.5K",
        "Clan Bruiser Lv 8.8K",
        "Clan Bruiser Lv 8K",
        "Clan Disciple Lv 6.5K",
        "Clan Disciple Lv 7K",
        "Clan Don Lv 10K",
        "Clan Prince Lv 9K",
        "Cloaked Deity Lv 1K",
        "Cloud Blader Lv 140",
        "Cloud Blader Lv 140M",
        "Corrupted Angel Lv 1.4M",
        "Councillor of Amos Lv 24.9Sx",
        "Councillor of Amos Lv 31.0Sx",
        "Crimson Dragoon Lv 100B",
        "Crimson Ozymandias Lv 4.7M",
        "Crimson Void Knight Lv 75M",
        "Crimson Void Knight Lv 95M",
        "Crimson Warlord Lv 4M",
        "Crimsonwrath, Master of Rage Lv 6M",
        "Cthulhu Lv 25Qd",
        "Cvezkly, Scion of Matter Lv 10T",
        "Damos, Guardian of Misfortune Lv 500K",
        "Darkseed Rampart Lv 100",
        "Deity of Eyes Lv 80",
        "Denizen of Plague Lv 170B",
        "Depths Fiend Lv 100K",
        "Desert Knight Lv 19",
        "Desert Knight Lv 23",
        "Desert Knight Lv 29",
        "Desert Knight Lv 31",
        "Desert Merchant Lv 29",
        "Domino Lv 100",
        "Dracoknight Brutus Lv 180M",
        "Dracoknight Brutus Lv 380M",
        "Dracoknight of Glaurung Lv 120M",
        "Dracoknight of Glaurung Lv 320M",
        "Dracoknight of Smaug Lv 100M",
        "Dracoknight of Smaug Lv 300M",
        "Dragoon Lv 1B",
        "Druid of the Wind Lv 5.8K",
        "Dwelling Reaver Lv 375K",
        "Earth Champion Lv 4.2K",
        "Earth Disciple Lv 1.8K",
        "Earth Disciple Lv 1.9K",
        "Earth Disciple Lv 2.1K",
        "Earth Disciple Lv 2.4K",
        "Earth Disciple Lv 2.5K",
        "Earth Disciple Lv 2.6K",
        "Earth Disciple Lv 2.8K",
        "Earth Disciple Lv 2K",
        "Eccentric Explorer Lv 200Sp",
        "Eerie Jester Lv 20T",
        "Eerie Jester Lv 2Qd",
        "Effigy of Kleos Lv 100M",
        "Ehalios, Master of Viridian Lv 1.2M",
        "Empyrean Astronomer Lv 50K",
        "Empyrean Minstrel Lv 50K",
        "Empyrean Minstrel Lv 75K",
        "Empyreus Lv 1M",
        "Envoy of Gluttony Lv 2T",
        "Erikson Lv 1.65B",
        "Farm Boy Lv 16",
        "Fire Clan Hillfighter Lv 650M",
        "Flame Champion Lv 3.3K",
        "Flame Disciple Lv 1.1K",
        "Flame Disciple Lv 1.2K",
        "Flame Disciple Lv 1.3K",
        "Flame Disciple Lv 1.4K",
        "Flame Disciple Lv 1K",
        "Flame Disciple Lv 600",
        "Flame Disciple Lv 700",
        "Flame Disciple Lv 800",
        "Flame Disciple Lv 900",
        "Fletch Lv 1.75B",
        "Forest Clan Hillfighter Lv 650M",
        "Forgotten Soul, Yorick Lv 14",
        "Forlorne Executor Lv 975K",
        "Frost Clan Hillfighter Lv 650M",
        "Frost Lich Lv 4.5B",
        "Gamma Crusader Lv 12.5Qn",
        "Gamma Crusader Lv 3.2Qn",
        "Gamma Crusader Lv 6.3Qn",
        "Gamma Lancer Lv 1.3Qn",
        "Gamma Lancer Lv 2.7Qn",
        "Gem Homunculi Lv 310",
        "Gem Homunculi Lv 600",
        "Ghost King Lv 25",
        "Ghost Lv 10",
        "Ghost Lv 7",
        "Ghost Lv 8",
        "Ghost Lv 9",
        "Ghost of the Tower Lv 1Sx",
        "Gigachad Ogre Lv 22",
        "Gigachad Ogre Lv 24",
        "Gigachad Ogre Lv 34",
        "Gigachad Ogre Lv 44",
        "Gigachad Ogre Lv 55",
        "Gilded Assassin Lv 350B",
        "Gilded Assassin Lv 450B",
        "Gilded Assassin Lv 550B",
        "Gilded Assassin Lv 750B",
        "Gilded Assassin Lv 800B",
        "Goblin Captain Lv 13",
        "Goblin Lv 1",
        "Goblin Lv 2",
        "Goblin Lv 3",
        "Goblin Lv 5",
        "Goblin Mage Lv 10",
        "Golem of Flames Lv 725",
        "Golem of Flames Lv 775",
        "Golem of Flames Lv 850",
        "Gravekeeper Lv 25",
        "Gravemaster Lv 125",
        "Great Golem Lv 850",
        "Great Ogre Lv 28",
        "Great Ogre Lv 32",
        "Great Ogre Lv 36",
        "Great Ogre Lv 40",
        "Grimglow Eternal Lv 600K",
        "Guardian of the Emerald Crest Lv 53K",
        "Guardian of the Fallen Crest Lv 17T",
        "Guardian of the Fallen Crest Lv 33T",
        "Guardian of the Fallen Crest Lv 53T",
        "Guardian of the Fallen Crest Lv 73T",
        "Guardian of the Fallen Crest Lv 83T",
        "Guardian of the Ruby Crest Lv 23K",
        "Gygax, Lord of Chance Lv 12.3K",
        "Harbinger of the End Lv 49.9O",
        "Harbinger of the End Lv 499O",
        "Harbinger of the End Lv 500Sp",
        "Heart of Desire Lv 4T",
        "Heckling Menace Lv 1.7K",
        "Heckling Menace Lv 2K",
        "High Councillor of Amos Lv 45Sx",
        "Highland Ogre Lv 14",
        "Highland Ogre Lv 15",
        "Highland Ogre Lv 18",
        "Highland Ogre Lv 22",
        "Highland Ogre Lv 33",
        "Highland Ogre Lv 37",
        "Highland Ogre Lv 40",
        "Ignister, Knight of the Dark Order Lv 25",
        "Illuminous Mage Lv 220M",
        "Illuminous Mage Lv 520M",
        "Indolent Seer Lv 10.0Sp",
        "Infantry of the Valkyrie Lv 10K",
        "Infantry of the Valkyrie Lv 2.5K",
        "Infantry of the Valkyrie Lv 25K",
        "Infantry of the Valkyrie Lv 5K",
        "Infernal Visor Lv 1.3M",
        "Inferno Mage Lv 900K",
        "Kappa Lv 14O",
        "Kappa Lv 3.00O",
        "Kappa Lv 7O",
        "Kappa Lv 9O",
        "Knight of the Empyrean Order Lv 120K",
        "Knight of the Empyrean Order Lv 90K",
        "Knight of the Silent Abyss Lv 50M",
        "Knight of the Silent Abyss Lv 5M",
        "Knight of the Silent Abyss Lv 90M",
        "Kronos of the Future Lv 1K",
        "Kronos of the Past Lv 100K",
        "Kronos, The Final Justice Lv 25M",
        "Kronos, the Flood of Oblivion Lv 2.5M",
        "Kronos, the Scorched Afterlife Lv 17.5M",
        "Lifecloak Berserker Lv 400K",
        "Lifecloak Rogue Lv 400K",
        "Lightning Clan Hillfighter Lv 650M",
        "Lone Goblin Lv 300Sp",
        "Lord of Greed Lv 3T",
        "Lord of the Magma Lv 9M",
        "Lord of the Void Lv 100T",
        "Lost Astrologian Lv 4M",
        "Mage of the Vile Truth Lv 6.3Qn",
        "Masked Fighter Lv 7",
        "Master of Destruction Lv 400M",
        "Master of Earth Lv 2.9K",
        "Master of Earth Lv 3K",
        "Master of Flames Lv 1.2K",
        "Master of Flames Lv 1.7K",
        "Master of Oceans Lv 3.9K",
        "Master of Oceans Lv 4.3K",
        "Master of Oceans Lv 4.4K",
        "Master of Sloth Lv 4.5T",
        "Master of Wind Lv 3.1K",
        "Master of Wind Lv 3.4K",
        "Master of Wind Lv 3K",
        "Meddling Soul Lv 40",
        "Meddling Soul Lv 45",
        "Meddling Soul Lv 53",
        "Meddling Soul Lv 58",
        "Meddling Soul Lv 66",
        "Meeboid Lv 140B",
        "Merman Lv 10K",
        "Merman Lv 12.5K",
        "Merman Lv 3.5K",
        "Merman Lv 5.5K",
        "Merman Soldier Lv 17.5K",
        "Merman Soldier Lv 32.5K",
        "Mobius, Servant of the Seakings Lv 7.5M",
        "Monk Lv 6.4K",
        "Monk Lv 64",
        "Moon Bunny Lv 60",
        "Mystic of Destruction Lv 160M",
        "Mystic of Destruction Lv 460M",
        "Necromancer Lv 60",
        "Ocean Champion Lv 4.1K",
        "Ocean Champion Lv 4.8K",
        "Ocean Champion Lv 4K",
        "Ocean Champion Lv 6.7K",
        "Ocean Delver Lv 560",
        "Ocean Disciple Lv 3.4K",
        "Ocean Disciple Lv 3.5K",
        "Ocean Disciple Lv 3.6K",
        "Ocean Disciple Lv 3.7K",
        "Ocean Emissary Lv 125K",
        "Ogam, Master of High Earth Lv 30",
        "Ogre King Lv 15",
        "Ogre Lv 12",
        "Ogre Lv 9",
        "Old Dissident Lv 11Sx",
        "Old Dissident Lv 5Sx",
        "Old Mage Lv 1.65B",
        "Pirate Goblin Lv 10",
        "Pirate Goblin Lv 7",
        "Pirate Goblin Lv 8",
        "Poor Villager Lv 15",
        "Poor Villager Lv 2",
        "Poor Villager Lv 25",
        "Poor Villager Lv 25K",
        "Prisoner of the Mind Lv 150Sp",
        "Prisoner of the Mind Lv 250Sp",
        "Prisoner of the Mind Lv 500Sp",
        "Putridosaurus Lv 53Qd",
        "Putridosaurus Lv 837Qd",
        "Rebuked Voidlord Lv 500B",
        "Rebuked Voidlord Lv 600B",
        "Red Rogue Lv 1.2K",
        "Rotten Merman Lv 115B",
        "Rotten Merman Lv 45B",
        "Rotten Merman Lv 65B",
        "Sage Knight Lv 20",
        "Sage Knight Lv 80",
        "Sage Knight Lv 90",
        "Scythrax, the Sharpest One Lv 199Sx",
        "Seaking Lv 80M",
        "Sealed Golem Lv 75K",
        "Seer of Contempt Lv 20.0Sp",
        "Serpent Lv 2K",
        "Serpent Lv 40",
        "Servant of Fire Lv 20",
        "Shadow Assassin Lv 24",
        "Shadow Assassin Lv 3",
        "Shadow Assassin Lv 5",
        "Snowman Lv 10",
        "Snowman Lv 15",
        "Snowman Lv 7",
        "Snowman Lv 8",
        "Splendor Knight Lv 220B",
        "Splendor Knight Lv 280B",
        "Stag of the Abyss Lv 13Qd",
        "Stomag, Guardian of Hatred Lv 5K",
        "Stone Acolyte Lv 275",
        "Stone Knight Lv 15K",
        "Stone Knight Lv 250",
        "Stone Knight Lv 300",
        "Stone Knight Lv 350",
        "Stone Knight Lv 400",
        "Stone Underling Lv 110",
        "Stone Underling Lv 130",
        "Stone Underling Lv 160",
        "Stone Underling Lv 170",
        "Stone Underling Lv 225",
        "Stone Underling Lv 325",
        "Straw Demon Lv 130",
        "Straw Demon Lv 80",
        "Sunken Captain Lv 60K",
        "Sunken Knight Lv 250K",
        "Sunken Knight Lv 275K",
        "Sunken Sniper Lv 13K",
        "Sunken Sniper Lv 8K",
        "Sunken Swashbuckler Lv 2.5K",
        "Sunken Swashbuckler Lv 4.5K",
        "Tarnished Guardia Lv 6Qd",
        "Tarnished Valkyrie Lv 295K",
        "The Gladiator Lv 25",
        "The Knightmare Lv 10B",
        "The Sheriff Lv 11",
        "The Silver King Lv 20O",
        "The Silver King Lv 49.9O",
        "Thief Lv 2",
        "Thief Lv 3",
        "Thief Lv 4",
        "Thief Lv 5",
        "Tokus, Viridian Scion Lv 1.2M",
        "Tokus, Viridian Scion Lv 12T",
        "Toothy Lv 1.25B",
        "Treachery Master Lv 700Qd",
        "Tyrant of Envy Lv 2.5T",
        "Tyrant of Pride Lv 5T",
        "Tyrant of Wrath Lv 1T",
        "Unholy Apparition Lv 1Qd",
        "Vanguard of Life Lv 200K",
        "Vespertilio Lv 2.3Sx",
        "Viking Leader Lv 35",
        "Viking Lv 15",
        "Viking Lv 30",
        "Viking Lv 50",
        "Viking Lv 60",
        "Viking Warlord Lv 70",
        "Viking of True Ice Lv 335",
        "Vilethorn Eternal Lv 800K",
        "Villager Lv 1",
        "Villager Lv 22",
        "Viridian Eviscerator Lv 300K",
        "Viridian Eviscerator Lv 600K",
        "Viridian Master Lv 1.6M",
        "Viridian Sorcerer Lv 300K",
        "Viridian Sorcerer Lv 450K",
        "Viridian Sorcerer Lv 500K",
        "Viridian Vanguard, Domani Lv 900K",
        "Voidking Lv 900T",
        "Wind Champion Lv 3.4K",
        "Wind Champion Lv 4K",
        "Wind Champion Lv 5.5K",
        "Wind Disciple Lv 2.4K",
        "Wind Disciple Lv 2.5K",
        "Wind Disciple Lv 2.6K",
        "Wind Disciple Lv 2.7K",
        "Wind Disciple Lv 2.8K",
        "Wind Disciple Lv 2.9K",
        "Winter Hunter Lv 16",
        "Winter Hunter Lv 24",
        "Winter Hunter Lv 27",
        "Winter Mage Lv 14",
        "Winter Nomad Lv 12",
        "Wizard of Arachnea Lv 6",
        "Woodland Hunter Lv 4",
        "Woodland Hunter Lv 7",
        "XP Goblin Lv 10K",
        "XP Goblin Lv 99",
        "XP Goblin Lv 999",
        "Yvexlorn, Ice Sunderer Lv 2.5K",
        "Yvexlorn, Ice Sunderer Lv 25",
        "clockwork, the Judge of Time Lv 100K",
 },
    ["Banland"] = {
 },
    ["Hall of Time"] = {
        "Kronos, The Final Justice Lv 25M",
        "Aureus, The Tarnished Lv 10M",
        "Viridian Master Lv 1.6M",
        "Ehalios, Master of Viridian Lv 1.2M",
        "Tokus, Viridian Scion Lv 1.2M",
        "Empyreus Lv 1M",
        "Viridian Vanguard, Domani Lv 900K",
        "Vilethorn Eternal Lv 800K",
        "Grimglow Eternal Lv 600K",
        "Viridian Eviscerator Lv 600K",
        "Viridian Sorcerer Lv 500K",
        "Viridian Sorcerer Lv 450K",
        "Lifecloak Berserker Lv 400K",
        "Lifecloak Rogue Lv 400K",
        "Viridian Sorcerer Lv 300K",
        "Viridian Eviscerator Lv 300K",
        "Tarnished Valkyrie Lv 295K",
        "Vanguard of Life Lv 200K",
        "Knight of the Empyrean Order Lv 120K",
        "clockwork, the Judge of Time Lv 100K",
        "Knight of the Empyrean Order Lv 90K",
        "Archer of Artemis Lv 85K",
        "Empyrean Minstrel Lv 75K",
        "Empyrean Astronomer Lv 50K",
        "Empyrean Minstrel Lv 50K",
        "Infantry of the Valkyrie Lv 25K",
        "Infantry of the Valkyrie Lv 10K",
        "Infantry of the Valkyrie Lv 5K",
        "Infantry of the Valkyrie Lv 2.5K",
 },
}
