return {
    ["Mirage"] = {
        "Ancient Wanderer Lv 10.0Sp",
        "Aureus, The Great Lv 7.77N",
        "Eccentric Explorer Lv 200Sp ",
        "Harbinger of the End Lv 49.9O ",
        "Harbinger of the End Lv 499O ",
        "Harbinger of the End Lv 500Sp ",
        "Indolent Seer Lv 10.0Sp",
        "Kappa Lv 14O ",
        "Kappa Lv 3.00O",
        "Kappa Lv 7O",
        "Kappa Lv 9O",
        "Lone Goblin Lv 300Sp ",
        "Prisoner of the Mind Lv 150Sp",
        "Prisoner of the Mind Lv 250Sp",
        "Prisoner of the Mind Lv 500Sp ",
        "Seer of Contempt Lv 20.0Sp",
        "The Silver King Lv 20O",
        "The Silver King Lv 49.9O",
 },
    ["Mines"] = {
        "Arcane Stone Knight Lv 450",
        "Arcane Stone Knight Lv 525",
        "Basalt Barbarian Lv 375",
        "Basalt Barbarian Lv 425",
        "Basalt Barbarian Lv 500",
        "Basalt Barbarian Lv 625",
        "Basalt Blader Lv 625",
        "Basalt Demon Lv 999",
        "Gem Homunculi Lv 310",
        "Gem Homunculi Lv 600",
        "Golem of Flames Lv 725",
        "Golem of Flames Lv 775",
        "Golem of Flames Lv 850",
        "Great Golem Lv 850",
        "Sealed Golem Lv 75K",
        "Serpent Lv 2K",
        "Stomag, Guardian of Hatred Lv 5000 ",
        "Stone Acolyte Lv 275",
        "Stone Knight Lv 250",
        "Stone Knight Lv 300",
        "Stone Knight Lv 350",
        "Stone Knight Lv 400",
        "Stone Underling Lv 110",
        "Stone Underling Lv 130",
        "Stone Underling Lv 160",
        "Stone Underling Lv 170",
        "Stone Underling Lv 225",
        "Stone Underling Lv 325",
        "XP Goblin Lv 99",
 },
    ["Underwater"] = {
        "Abandoned Knight Lv 700K",
        "Aqua Mage Lv 85K",
        "Cardinal of Poseidon Lv 4M",
        "Cardinal of Treasure Lv 2M",
        "Cerulean Ozymandias Lv 4.7M",
        "Corrupted Angel Lv 1.4M",
        "Crimson Ozymandias Lv 4.7M",
        "Crimson Void Knight Lv 75000000 ",
        "Crimson Void Knight Lv 95M",
        "Crimson Warlord Lv 4M",
        "Crimsonwrath, Master of Rage Lv 6M",
        "Damos, Guardian of Misfortune Lv 500K",
        "Depths Fiend Lv 100K",
        "Dwelling Reaver Lv 375K",
        "Effigy of Kleos Lv 100M ",
        "Forlorne Executor Lv 975K",
        "Infernal Visor Lv 1.3M",
        "Inferno Mage Lv 900K",
        "Knight of the Silent Abyss Lv 50M",
        "Knight of the Silent Abyss Lv 90M",
        "Kronos, the Flood of Oblivion Lv 2.5M",
        "Kronos, the Scorched Afterlife Lv 17.5M",
        "Lord of the Magma Lv 9M",
        "Lost Astrologian Lv 4000000 ",
        "Mobius, Servant of the Seakings Lv 7.5M",
        "Ocean Emissary Lv 125K",
        "Rotten Merman Lv 115B",
        "Rotten Merman Lv 45B",
        "Rotten Merman Lv 65B",
        "Seaking Lv 80M",
        "Sunken Knight Lv 250K",
        "Sunken Knight Lv 275K",
 },
    ["Void Tower"] = {
        "Agnar, Revoked Captain of the Dracoknights Lv 125Sx ",
        "Almighty Ghost Lv 30Sx",
        "Almighty Ghost Lv 70Sx",
        "Amos, Priest of the Forgone Lv 666Sx",
        "Chronobonum, Everangel Lv 10T",
        "Councillor of Amos Lv 24.9Sx",
        "Councillor of Amos Lv 31.0Sx",
        "Councillor of Amos Lv 31.0Sx ",
        "Ghost of the Tower Lv 1Sx",
        "High Councillor of Amos Lv 45Sx",
        "Old Dissident Lv 11Sx",
        "Old Dissident Lv 5Sx",
        "Scythrax, the Sharpest One Lv 199Sx",
 },
    ["Hall of Time"] = {
        "Archer of Artemis Lv 85K",
        "Aureus, The Tarnished Lv 10M",
        "Ehalios, Master of Viridian Lv 1200000 ",
        "Empyrean Astronomer Lv 50K",
        "Empyrean Minstrel Lv 50K",
        "Empyrean Minstrel Lv 75K",
        "Empyreus Lv 1M",
        "Grimglow Eternal Lv 600000 ",
        "Grimglow Eternal Lv 600K",
        "Infantry of the Valkyrie Lv 10K",
        "Infantry of the Valkyrie Lv 2.5K",
        "Infantry of the Valkyrie Lv 25K",
        "Infantry of the Valkyrie Lv 5K",
        "Knight of the Empyrean Order Lv 120K",
        "Knight of the Empyrean Order Lv 90K",
        "Kronos, The Final Justice Lv 25M",
        "Lifecloak Berserker Lv 400000 ",
        "Lifecloak Berserker Lv 400K",
        "Lifecloak Rogue Lv 400000 ",
        "Lifecloak Rogue Lv 400K",
        "Tarnished Valkyrie Lv 295K",
        "Tokus, Viridian Scion Lv 1.2M",
        "Vanguard of Life Lv 200K",
        "Vilethorn Eternal Lv 800K",
        "Viridian Eviscerator Lv 300K",
        "Viridian Eviscerator Lv 600000 ",
        "Viridian Master Lv 1.6M",
        "Viridian Sorcerer Lv 300K",
        "Viridian Sorcerer Lv 450000 ",
        "Viridian Sorcerer Lv 500K",
        "Viridian Vanguard, Domani Lv 900K",
        "clockwork, the Judge of Time Lv 100K",
 },
    ["Fools"] = {
        "Aguman Lv 20",
 },
    ["Athenia"] = {
        "Aguman Lv 20000 ",
        "Aleph, Master of the Blind Lv 7.5K",
        "Athenian Merchant Lv 400 ",
        "Athenian Villager Lv 2000 ",
        "Athenian Warrior Lv 1.1K",
        "Athenian Warrior Lv 1.5K",
        "Athenian Warrior Lv 900",
        "Clan Bruiser Lv 8000 ",
        "Clan Bruiser Lv 8250 ",
        "Clan Bruiser Lv 8500 ",
        "Clan Bruiser Lv 8750 ",
        "Clan Bruiser Lv 8K",
        "Clan Disciple Lv 6.5K",
        "Clan Disciple Lv 6500 ",
        "Clan Disciple Lv 7K",
        "Clan Don Lv 10K",
        "Clan Prince Lv 9000 ",
        "Druid of the Wind Lv 5800 ",
        "Earth Champion Lv 4.2K",
        "Earth Disciple Lv 1.8K",
        "Earth Disciple Lv 1.9K",
        "Earth Disciple Lv 2.4K",
        "Earth Disciple Lv 2.5K",
        "Earth Disciple Lv 2.6K",
        "Earth Disciple Lv 2.8K",
        "Earth Disciple Lv 2100 ",
        "Earth Disciple Lv 2450 ",
        "Earth Disciple Lv 2K",
        "Flame Champion Lv 3.3K",
        "Flame Disciple Lv 1.1K",
        "Flame Disciple Lv 1.2K",
        "Flame Disciple Lv 1300 ",
        "Flame Disciple Lv 1400 ",
        "Flame Disciple Lv 1K",
        "Flame Disciple Lv 600",
        "Flame Disciple Lv 700",
        "Flame Disciple Lv 800",
        "Flame Disciple Lv 900",
        "Guardian of the Emerald Crest Lv 53K",
        "Guardian of the Ruby Crest Lv 23K",
        "Heckling Menace Lv 1.7K",
        "Heckling Menace Lv 2000 ",
        "Heckling Menace Lv 2K",
        "Master of Earth Lv 2.9K",
        "Master of Earth Lv 2950 ",
        "Master of Earth Lv 3K",
        "Master of Flames Lv 1.2K",
        "Master of Flames Lv 1200 ",
        "Master of Flames Lv 1700 ",
        "Master of Oceans Lv 3.9K",
        "Master of Oceans Lv 4.3K",
        "Master of Oceans Lv 4.4K",
        "Master of Wind Lv 3100 ",
        "Master of Wind Lv 3400 ",
        "Master of Wind Lv 3K",
        "Ocean Champion Lv 4.1K",
        "Ocean Champion Lv 4.8K",
        "Ocean Champion Lv 4K",
        "Ocean Champion Lv 6.7K",
        "Ocean Disciple Lv 3.4K",
        "Ocean Disciple Lv 3.5K",
        "Ocean Disciple Lv 3.6K",
        "Ocean Disciple Lv 3.7K",
        "Poor Villager Lv 25000 ",
        "Stone Knight Lv 15K",
        "Wind Champion Lv 3.4K",
        "Wind Champion Lv 4K",
        "Wind Champion Lv 5500 ",
        "Wind Disciple Lv 2.5K",
        "Wind Disciple Lv 2.6K",
        "Wind Disciple Lv 2.7K",
        "Wind Disciple Lv 2.8K",
        "Wind Disciple Lv 2.9K",
        "Wind Disciple Lv 2400 ",
        "XP Goblin Lv 10K",
        "XP Goblin Lv 999",
 },
    ["Default"] = {
        "Armored Barbarian Lv 80",
        "Bandit Chief Lv 7",
        "Berserker Lv 22",
        "Berserker Lv 50",
        "Berserker Lv 60",
        "Berserker Lv 7",
        "Berserker Lv 70",
        "Berserker Lv 90",
        "Berserker Master Lv 125",
        "Black Iron Invader Lv 60",
        "Bluesteel Commander Lv 60",
        "Bluesteel Sage Lv 80",
        "Bone Harvester Lv 75",
        "Bone Harvester Lv 75 ",
        "Bunny Lv 3",
        "Bunny Lv 6",
        "Castle Bandit Lv 40",
        "Castle Bandit Lv 60",
        "Castle Bandit Lv 70",
        "Castle Knight Lv 100",
        "Catseye Deity Lv 100",
        "Chad Barbarian Lv 70",
        "Cielo de la asad from devil beater Lv 1000000 ",
        "Cloaked Deity Lv 1K",
        "Cloud Blader Lv 140 ",
        "Darkseed Rampart Lv 100",
        "Deity of Eyes Lv 80",
        "Desert Knight Lv 19",
        "Desert Knight Lv 23",
        "Desert Knight Lv 29",
        "Desert Knight Lv 31",
        "Desert Merchant Lv 29 ",
        "Domino Lv 100",
        "Farm Boy Lv 16",
        "Forgotten Soul, Yorick Lv 14 ",
        "Ghost King Lv 25",
        "Ghost Lv 10",
        "Ghost Lv 7",
        "Ghost Lv 8",
        "Ghost Lv 9",
        "Gigachad Ogre Lv 22",
        "Gigachad Ogre Lv 24",
        "Gigachad Ogre Lv 34",
        "Gigachad Ogre Lv 44",
        "Gigachad Ogre Lv 55",
        "Goblin Captain Lv 13",
        "Goblin Lv 1",
        "Goblin Lv 2",
        "Goblin Lv 3",
        "Goblin Lv 5",
        "Goblin Mage Lv 10",
        "Gravekeeper Lv 25",
        "Gravemaster Lv 125",
        "Great Ogre Lv 28 ",
        "Great Ogre Lv 32",
        "Great Ogre Lv 36",
        "Great Ogre Lv 40 ",
        "Highland Ogre Lv 14",
        "Highland Ogre Lv 15",
        "Highland Ogre Lv 18",
        "Highland Ogre Lv 22",
        "Highland Ogre Lv 33",
        "Highland Ogre Lv 37",
        "Highland Ogre Lv 40",
        "Ignister, Knight of the Dark Order Lv 25",
        "Knight of the Silent Abyss Lv 5M",
        "Kronos of the Past Lv 100K",
        "Masked Fighter Lv 7",
        "Meddling Soul Lv 40",
        "Meddling Soul Lv 45 ",
        "Meddling Soul Lv 53",
        "Meddling Soul Lv 58",
        "Meddling Soul Lv 66",
        "Merman Lv 12.5K",
        "Merman Lv 3.5K",
        "Merman Lv 5.5K",
        "Merman Soldier Lv 17.5K",
        "Merman Soldier Lv 32.5K",
        "Moon Bunny Lv 60",
        "Necromancer Lv 60",
        "Ogam, Master of High Earth Lv 30",
        "Ogre King Lv 15",
        "Ogre Lv 12",
        "Ogre Lv 9",
        "Pirate Goblin Lv 10",
        "Pirate Goblin Lv 7",
        "Pirate Goblin Lv 8",
        "Poor Villager Lv 15",
        "Poor Villager Lv 2",
        "Poor Villager Lv 25",
        "Sage Knight Lv 20",
        "Sage Knight Lv 80",
        "Sage Knight Lv 90",
        "Serpent Lv 40",
        "Servant of Fire Lv 20",
        "Shadow Assassin Lv 24",
        "Shadow Assassin Lv 3",
        "Shadow Assassin Lv 3 ",
        "Shadow Assassin Lv 5",
        "Snowman Lv 10",
        "Straw Demon Lv 130",
        "Straw Demon Lv 80",
        "Sunken Captain Lv 60000 ",
        "Sunken Sniper Lv 13000 ",
        "Sunken Sniper Lv 8000 ",
        "Sunken Swashbuckler Lv 2500 ",
        "Sunken Swashbuckler Lv 4500 ",
        "The Gladiator Lv 25 ",
        "The Sheriff Lv 11",
        "Thief Lv 2",
        "Thief Lv 3",
        "Thief Lv 4",
        "Thief Lv 5",
        "Viking Leader Lv 35",
        "Viking Lv 15 ",
        "Viking Lv 30",
        "Viking Lv 50",
        "Viking Lv 60",
        "Viking Warlord Lv 70",
        "Villager Lv 1",
        "Villager Lv 22",
        "Wizard of Arachnea Lv 6",
        "Woodland Hunter Lv 4",
        "Woodland Hunter Lv 7",
 },
    ["Glaurung"] = {
        "Assassin of the Silent Abyss Lv 25T",
        "Assassin of the Silent Abyss Lv 25T ",
        "Bombastic Ninja Lv 6.75B",
        "Bombastic Ninja Lv 9.75B",
        "Boulder Sage Lv 20B",
        "Heart of Desire Lv 4T",
        "The Knightmare Lv 10B",
 },
    ["Void"] = {
        "Alpha Biograft Delver Lv 411Qn",
        "Alpha Biograft Delver Lv 97Qn",
        "Assassin of the Silent Abyss Lv 19Qd",
        "Baron Voidling Lv 300B",
        "Baron Voidling Lv 400B",
        "Baron Voidling Lv 700B",
        "Cthulhu Lv 25Qd",
        "Unholy Apparition Lv 1Qd",
        "Cvezkly, Scion of Matter Lv 10T",
        "Denizen of Plague Lv 170B",
        "Eerie Jester Lv 20T",
        "Envoy of Gluttony Lv 2T",
        "Gamma Crusader Lv 12.5Qn",
        "Gamma Crusader Lv 3.2Qn",
        "Gamma Crusader Lv 6.3Qn",
        "Gamma Lancer Lv 1.3Qn",
        "Gamma Lancer Lv 2.7Qn",
        "Gilded Assassin Lv 350B",
        "Gilded Assassin Lv 450B",
        "Gilded Assassin Lv 550B",
        "Gilded Assassin Lv 750B",
        "Gilded Assassin Lv 800B",
        "Guardian of the Fallen Crest Lv 17T",
        "Guardian of the Fallen Crest Lv 33T",
        "Guardian of the Fallen Crest Lv 53T",
        "Guardian of the Fallen Crest Lv 53T ",
        "Guardian of the Fallen Crest Lv 73T",
        "Guardian of the Fallen Crest Lv 83T",
        "Lord of Greed Lv 3T ",
        "Lord of the Void Lv 100T",
        "Mage of the Vile Truth Lv 6.3Qn",
        "Master of Sloth Lv 4.5T",
        "Meeboid Lv 140B",
        "Meeboid Lv 140B ",
        "Putridosaurus Lv 53Qd",
        "Putridosaurus Lv 837Qd",
        "Rebuked Voidlord Lv 500B",
        "Rebuked Voidlord Lv 600B",
        "Splendor Knight Lv 220B",
        "Splendor Knight Lv 220B ",
        "Splendor Knight Lv 280B",
        "Splendor Knight Lv 280B ",
        "Stag of the Abyss Lv 13Qd",
        "Tarnished Guardia Lv 6Qd",
        "Tokus, Viridian Scion Lv 12T",
        "Treachery Master Lv 700Qd",
        "Tyrant of Envy Lv 2.5T",
        "Tyrant of Pride Lv 5T",
        "Tyrant of Wrath Lv 1T",
        "Vespertilio Lv 2.3Sx",
        "Voidking Lv 900T",
 },
    ["Citadel"] = {
        "Azure Samurai Lv 3.75B",
        "Azurewrath Demon Lv 2.65B",
        "Azurewrath, Lord of  the Frost Lv 5B",
        "Champion of Azurewrath Lv 200M",
        "Cloud Blader Lv 140M",
        "Crimson Dragoon Lv 100B",
        "Dracoknight Brutus Lv 180M",
        "Dracoknight Brutus Lv 380M",
        "Dracoknight of Glaurung Lv 120M",
        "Dracoknight of Glaurung Lv 320M",
        "Dracoknight of Smaug Lv 100M",
        "Dracoknight of Smaug Lv 300M",
        "Dragoon Lv 1B",
        "Erikson Lv 1.65B",
        "Fire Clan Hillfighter Lv 650M",
        "Fletch Lv 1.75B",
        "Forest Clan Hillfighter Lv 650M",
        "Frost Clan Hillfighter Lv 650M",
        "Frost Lich Lv 4.5B",
        "Illuminous Mage Lv 220M",
        "Illuminous Mage Lv 520M",
        "Lightning Clan Hillfighter Lv 650M",
        "Master of Destruction Lv 400M",
        "Mystic of Destruction Lv 160M",
        "Mystic of Destruction Lv 460M",
        "Old Mage Lv 1.65B",
        "Toothy Lv 1.25B",
 },
    ["Grandia"] = {
        "Abyss Master Lv 666De",
        "Alphas Lv 7Ud ",
        "Angel Statue Lv 1",
        "Archduke of the Federation Lv 8DD",
        "Azure Prisoner Lv 200N ",
        "Azure Prisoner Lv 300N",
        "Azure Prisoner Lv 300N ",
        "Azure Prisoner Lv 600N",
        "Azure Prisoner Lv 600N ",
        "Azure Prisoner Lv 700N ",
        "Basal Demon Lv 20N",
        "Basal Demon Lv 5N",
        "Basal Demon Lv 5N ",
        "Basal Knight Lv 10De ",
        "Basal Knight Lv 300De",
        "Basal Knight Lv 40De ",
        "Basal Knight Lv 6.99De ",
        "Basal Knight Lv 80De",
        "Basal Knight Lv 80De ",
        "Basal Knight Lv 8De ",
        "Cellar Vampire Lv 160Ud ",
        "Cellar Vampire Lv 320Ud",
        "Cellar Vampire Lv 70Ud ",
        "Chronobonum, Everangel Lv 10Ud ",
        "Constable Aryx Lv 9DD",
        "Court Assassin Lv 9Ud",
        "Cursed Demon Lv 13N",
        "Cursed Demon Lv 13N ",
        "Cursed Demon Lv 89.9N",
        "Cyber Soldier Lv 1.5De ",
        "Cyber Soldier Lv 650N",
        "Cyber Soldier Lv 650N ",
        "Cyber Soldier Lv 850N ",
        "Cyber Soldier Lv 8De",
        "Disgraced Merman Lv 2N",
        "Disgraced Merman Lv 2N ",
        "Disgraced Merman Lv 8N",
        "Disgraced Merman Lv 8N ",
        "Final Knight of the Silent Abyss Lv 2Ud",
        "Ghost King Lv 2.5De",
        "Glaurung Lv 990De ",
        "Grand Vampire Lv 3.09DD",
        "Grand Vampire Lv 7.00DD",
        "Grand Vampire Lv 700Ud",
        "Gravekeeper Lv 250N",
        "Gravekeeper Lv 500N",
        "Haunting Grin Lv 33.3De",
        "Inner Basal Archer Lv 500De",
        "Inner Basal Guard Lv 500De",
        "Inner Basal Guard Lv 90De",
        "Lord of the Federation Lv 1tdD",
        "Omegas Lv 7Ud ",
        "Seaking Lv 800De ",
        "Steel Samurai Lv 2Ud",
        "Voidking Lv 900De",
 },
    ["Hub of Rebirth"] = {
        "Bone Harvester Lv 5K",
        "Gygax, Lord of Chance Lv 12345 ",
        "Kronos of the Future Lv 1K",
        "Monk Lv 6.4K",
        "Monk Lv 64",
        "Ocean Delver Lv 560",
        "Red Rogue Lv 1.2K",
        "Viking of True Ice Lv 335",
        "XP Goblin Lv 99",
        "Yvexlorn, Ice Sunderer Lv 2.5K",
 },
}
